---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - lineinfile:
        path: /var/www/html/index.html
        regexp: '^<br>application_password='
        line: 'application_password=newpass'
      notify:
        - start httpd
        - insert a print
  handlers:
    - name: start httpd
      service: name=httpd state=restarted
    -
